name: Build

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/build.yml'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v5
        with:
          go-version-file: go.mod

      - name: Check formatting and run go vet
        run: make lint

      - name: Run tests
        run: make test

      - name: Compile code
        run: make
