name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
          path: go/src/github.com/mdeous/dnscheck

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.16

      - name: Install gox
        run: go get github.com/mitchellh/gox

      - name: Build
        run: make cross-compile
        env:
          PATH: "${GOPATH}/bin:${PATH}"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/dnscheck-*"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          omitBody:  true
