name: Release

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/release.yml'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v5
        with:
          go-version: ^1.16

      - name: Install gox
        run: go install github.com/mitchellh/gox@latest

      - name: Build
        run: make cross-compile

      - name: Get release version
        id: get_version
        run: |
          version=""
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            version="nightly"
          else
            version="$(make version)"
          fi
          echo "Version: ${version}"
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Publish release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ github.ref == 'refs/heads/main' }}
          name: ${{ steps.get_version.outputs.version }}
          files: |
            build/dnscheck-*
